# Generated by Django 3.2.16 on 2024-01-01 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLogSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_time', models.DateTimeField(auto_now=True, db_column='search_time')),
                ('music_name', models.CharField(db_column='music_name', max_length=255)),
                ('from_db', models.CharField(db_column='from_db', max_length=255)),
                ('user_ip', models.CharField(db_column='user_ip', max_length=255)),
            ],
            options={
                'db_table': 'search_access_log',
            },
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=1000)),
                ('artist', models.CharField(db_column='artist', max_length=1000)),
                ('duration', models.CharField(blank=True, db_column='duration', max_length=1000)),
                ('album', models.CharField(db_column='album', max_length=1000)),
                ('released_data', models.CharField(db_column='released_data', max_length=1000)),
                ('pic', models.CharField(db_column='pic', max_length=1000)),
                ('url', models.CharField(blank=True, db_column='url', max_length=1000)),
            ],
            options={
                'db_table': 'music_info',
            },
        ),
    ]
